# Generated by Django 4.2.5 on 2023-09-10 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=100)),
                ("amount", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("kzt", "Tenge"),
                            ("eur", "Euro"),
                            ("usd", "Dollar"),
                            ("rub", "Ruble"),
                        ],
                        default="kzt",
                        max_length=3,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime(
                            2023,
                            9,
                            10,
                            18,
                            36,
                            19,
                            527790,
                            tzinfo=datetime.timezone.utc,
                        ),
                    ),
                ),
            ],
        ),
    ]
