# Generated by Django 4.2.5 on 2023-11-15 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("kzt", "Tenge"),
                            ("eur", "Euro"),
                            ("usd", "Dollar"),
                            ("rub", "Ruble"),
                            ("sum", "Sums"),
                        ],
                        default="kzt",
                        max_length=3,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_considered_debt", models.BooleanField(default=True)),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        default="N/A",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="expenses.category",
                    ),
                ),
                (
                    "who_paid",
                    models.ForeignKey(
                        help_text="The one who spends the money",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("split_proportion", models.IntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split",
                        to="expenses.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
