# Generated by Django 4.2.5 on 2023-11-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="N/A",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="expenses.category",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
