# Generated by Django 4.2.5 on 2023-11-15 05:31

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_category_options_alter_expense_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=models.SET(expenses.models.get_or_create_default_category),
                to="expenses.category",
            ),
        ),
    ]
