# Generated by Django 4.2.5 on 2023-09-10 18:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_expense_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 9, 10, 18, 36, 37, 186031, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
