# Generated by Django 4.2.5 on 2023-11-05 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0004_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_considered_debt",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="who_paid",
            field=models.ForeignKey(
                default=1,
                help_text="The one who spends the money",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.CharField(
                choices=[
                    ("kzt", "Tenge"),
                    ("eur", "Euro"),
                    ("usd", "Dollar"),
                    ("rub", "Ruble"),
                    ("sum", "Sums"),
                ],
                default="kzt",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Split_by_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("split_proportion", models.IntegerField()),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split",
                        to="expenses.expense",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
